config/routes.rb
Piccy::Application.routes.draw do
  resources :pictures

  root :to => 'pictures#index'
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  has_attached_file :file, :styles => { :medium => "300x300>", :thumb => "50x50>" }

  before_save do |pic|
    pic.name = pic.file.original_filename if pic.name.blank?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  # GET /pictures
  # GET /pictures.json
  def index
    @pictures = Picture.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pictures }
    end
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
    @picture = Picture.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @picture }
    end
  end

  # GET /pictures/new
  # GET /pictures/new.json
  def new
    @picture = Picture.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @picture }
    end
  end

  # GET /pictures/1/edit
  def edit
    @picture = Picture.find(params[:id])
  end

  # POST /pictures
  # POST /pictures.json
  def create
    @picture = Picture.new(params[:picture])

    respond_to do |format|
      if @picture.save
        format.html { redirect_to @picture, notice: 'Picture was successfully created.' }
        format.json {
          render :json => [{
            :name           => @picture.name,
            :size           => @picture.file.size,
            :url            => @picture.file.url,
            :thumbnail_url  => @picture.file.url(:thumb),
            :delete_url     => picture_path(@picture),
            :delete_type    => "DELETE"
          }]
        }
      else
        format.html { render action: "new" }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pictures/1
  # PUT /pictures/1.json
  def update
    @picture = Picture.find(params[:id])

    respond_to do |format|
      if @picture.update_attributes(params[:picture])
        format.html { redirect_to @picture, notice: 'Picture was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture = Picture.find(params[:id])
    @picture.destroy

    respond_to do |format|
      format.html { redirect_to pictures_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Piccy</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Piccy
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = yield :javascript
    = yield :stylesheet
  %body
    = yield

app/views/pictures/_form.html.haml
= content_for :javascript do
  :javascript
    $(function () {
      $('#picture_file').fileupload({
          dataType: 'json',
          url: $('form').attr('action')+'.json',
          done: function (e, data) {
              $.each(data.result, function (index, file) {
                  var para = $('<p/>').text(file.name)
                  var imgt = $('<img/>').attr('src', file.thumbnail_url);
                  imgt.appendTo(para);
                  para.appendTo(document.body);
              });
          }
      });
    });


= form_for @picture do |f|
  -if @picture.errors.any?
    #error_explanation
      %h2= "#{pluralize(@picture.errors.count, "error")} prohibited this picture from being saved:"
      %ul
        - @picture.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :file
    = f.file_field :file
  .actions
    = f.submit 'Save'

app/views/pictures/edit.html.haml
%h1 Editing picture

= render 'form'

= link_to 'Show', @picture
\|
= link_to 'Back', pictures_path

app/views/pictures/index.html.haml
%h1 Listing pictures

%table
  %tr
    %th Name
    %th
    %th
    %th

  - @pictures.each do |picture|
    %tr
      %td= picture.name
      %td= link_to 'Show', picture
      %td= link_to 'Edit', edit_picture_path(picture)
      %td= link_to 'Destroy', picture, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Picture', new_picture_path

app/views/pictures/new.html.haml
%h1 New picture

= render 'form'

= link_to 'Back', pictures_path

app/views/pictures/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @picture.name

= link_to 'Edit', edit_picture_path(@picture)
\|
= link_to 'Back', pictures_path